[package]
name = "proxypass"
version = "0.1.0"
edition = "2021"
description = "A lightweight PAC-aware HTTP proxy with OS keychain auth and simple CLI"
license = "MIT"
repository = "https://github.com/ruicout0/proxypass"

[[bin]]
name = "proxypass"
path = "src/main.rs"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "sync", "time"] }

# HTTP proxy engine
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"

# TLS
rustls-native-certs = "0.7"

# PAC evaluation (QuickJS)
rquickjs = { version = "0.6", default-features = false, features = ["classes", "properties", "array-buffer"] }

# Auth (Kerberos/Negotiate) — not available on Windows, use SSPI instead
[target.'cfg(not(target_os = "windows"))'.dependencies]
libgssapi = { version = "0.11" }

# Config
toml = "0.8"
serde = { version = "1", features = ["derive"] }

# Keychain
keyring = { version = "3", features = ["apple-native"] }

# CLI
clap = { version = "4", features = ["derive"] }

# Utilities
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"
reqwest = { version = "0.12", features = ["rustls-tls", "native-tls-alpn", "http2"], default-features = false }
bytes = "1"
rpassword = "7"
libc = "0.2"
base64 = "0.22"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
